# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qryptic < Formula
  desc "Qryptic Client to connect to Qryptic gateways"
  homepage "https://github.com/leetsecure/qryptic-client-cli"
  version "0.1.0"
  license "AGPL-3.0"

  depends_on "go"
  depends_on "wireguard-tools"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leetsecure/qryptic-client-cli/releases/download/v0.1.0/qryptic_v0.1.0_Darwin_x86_64.tar.gz"
      sha256 "ef9fcb75a3823be54876e549c5fef90f725aa86ec33ff2e181533c31591c603c"

      def install
        bin.install "qryptic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leetsecure/qryptic-client-cli/releases/download/v0.1.0/qryptic_v0.1.0_Darwin_arm64.tar.gz"
      sha256 "c9d5c02214c82b7745ea167f5748046617db4037205517631c0a0572bccf8851"

      def install
        bin.install "qryptic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leetsecure/qryptic-client-cli/releases/download/v0.1.0/qryptic_v0.1.0_Linux_x86_64.tar.gz"
        sha256 "9f01ad3e809786b70e92ed61a45fe942f7b272d202308b8ef46c033b52434ecf"

        def install
          bin.install "qryptic"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leetsecure/qryptic-client-cli/releases/download/v0.1.0/qryptic_v0.1.0_Linux_arm64.tar.gz"
        sha256 "5d73584ba6472d42fc76e5f74f2e8f08cd8597f805e46af089e686cbd4d47aa7"

        def install
          bin.install "qryptic"
        end
      end
    end
  end

  test do
    system "#{bin}/qryptic --version"
  end
end
